name: Build and Push Docker images

on:
  push:
    branches:
      - main   
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      

      - name: Build and push Telegram Bot
        uses: docker/build-push-action@v5
        with:
          context: "./Backend/Telegram Bot"
          file: "./Backend/Telegram Bot/Dockerfile"
          push: true
          tags: |
            ghcr.io/aguilam/project-gems/telegram-bot:latest
            ghcr.io/aguilam/project-gems/telegram-bot:${{ github.sha }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: "./Backend/LLM Backend"
          file: "./Backend/LLM Backend/Dockerfile"
          push: true
          tags: |
            ghcr.io/aguilam/project-gems/backend:latest
            ghcr.io/aguilam/project-gems/backend:${{ github.sha }}
